name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Artifact name
          name: github-pages
          # Path of the directory containing the static assets.
          path: dist/ # default is _site/
          # Duration after which artifact will expire in days.
          # retention-days: # optional, default is 1
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          # GitHub token
          token: ${{ github.token }}
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
          # timeout: # optional, default is 600000
          # Maximum number of status report errors before cancelling a deployment (default: 10)
          # error_count: # optional, default is 10
          # Time in milliseconds between two deployment status report (default: 5 seconds)
          # reporting_interval: # optional, default is 5000
          # Name of the artifact to deploy
          artifact_name: github-pages
          # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
          # preview: # optional, default is false
